### ISSUE TITLE
Dep checker potential error

### ISSUE THREAD

**Issue by Bowarc** [Bowarc/chess_game#25]
https://github.com/Bowarc/chess_game/blob/main/scripts/dependency_checker.py#L69

This is matching on specific string, if the user adds  a space this fuck up

In general this script could reeally use a TOML parser for simplicity

**Comment by hugolz** [comment]
No, im removing all spaces at the start of the loop

**Comment by Bowarc** [comment]
No im removing all spaces at the start of the loop
