### ISSUE TITLE
Asset loader cpu intensive loop

### ISSUE THREAD

**Issue by Bowarc** [Bowarc/chess_game#42]
Currently the loader thread is running in a loop that is only slowed by a 10ms test delay.

The fix could be: run at 10 tps, but if you got a request on this update, dont sleep this frame.

**Comment by Bowarc** [comment]
Or simply just set [this line](https://github.com/Bowarc/chess_game/blob/main/client%2Fsrc%2Fassets%2Floader%2Fmod.rs#L47] to a blocking `.recv()`

**Comment by hugolz** [comment]
Fixed in [53c4d3d](https://github.com/Bowarc/chess_game/commit/53c4d3dd46a9bda067adafcffde274c580ff81c4)
